#include "random_engine.h"
//#include <random>
#include "vmath.h"

//std::mt19937 random_engine::generator;
uint32_t random_engine::lastseed = 1337;    // first initialisation

random_engine::random_engine()
  : seed(lastseed++) {
  /// Default constructor
  //std::cout << "DEBUG: random object constructed with seed " << seed << std::endl;
}

random_engine::~random_engine() {
  /// Default destructor
}

void random_engine::random_reset(){
  /// Re-seed the generator with its saved seed
  generator.seed(seed);
}

double random_engine::get_random_double(double from, double to) {
  std::uniform_real_distribution<double> distribution(from, to);
  return distribution(generator);
}
int random_engine::get_random_int(int from, int to) {
  std::uniform_int_distribution<int> distribution(from, to);
  return distribution(generator);
}
unsigned int random_engine::get_random_uint(unsigned int from, unsigned int to) {
  std::uniform_int_distribution<unsigned int> distribution(from, to);
  return distribution(generator);
}
bool random_engine::get_random_bool(double trueprobability) {
  std::bernoulli_distribution distribution(trueprobability);
  return distribution(generator);
}

double random_engine::get_angle_degrees() {
  return get_random_double(0.0, 360.0);
}
double random_engine::get_angle_radians() {
  return get_random_double(0.0, 2.0 * M_PI);
}

char random_engine::get_random_char_alpha_upper() {
  /// Return random ascii value for A-Z
  return get_random_uint(65, 90);
}
char random_engine::get_random_char_alphanum_upper() {
  /// Return random ascii value for 0-9 A-Z
  // include the entire range from 0 to Z, see http://www.asciitable.com/
  char result(get_random_uint(48, 90 - 7));
  // bridge the gap between 9 and A
  if(result > 39) {
    result += 7;
  }
  return result;
}
char random_engine::get_random_char_digit() {
  /// Return random ascii value for 0-9
  return get_random_uint(48, 57);
}

std::string random_engine::get_random_noun() {
  // TODO
  return "teapot";
}
std::string random_engine::get_random_verb() {
  // TODO
  return "sneaky";
}
std::string random_engine::get_random_name_male() {
  /// Return a male forename
  return malenames[get_random_uint(0, malenames_max)];
}
std::string random_engine::get_random_name_female() {
  /// Return a female forename
  return femalenames[get_random_uint(0, femalenames_max)];
}
std::string random_engine::get_random_name_neuter() {
  /// Return a gender-neutral forename
  return neuternames[get_random_uint(0, neuternames_max)];
}
std::string random_engine::get_random_name_surname() {
  /// Return a surname (always gender neutral)
  return surnames[get_random_uint(0, surnames_max)];
}
std::string random_engine::get_random_name_greek() {
  /// Return an ancient greek mythological name
  return greeknames[get_random_uint(0, greeknames_max)];
}
std::string random_engine::get_random_name_roman() {
  /// Return an ancient roman mythological name
  return romannames[get_random_uint(0, romannames_max)];
}
std::string random_engine::get_random_name_ancient() {
  /// Return an ancient mythological name of some kind
  if(get_random_bool()) {
    return get_random_name_greek();
  } else {
    return get_random_name_roman();
  }
}

std::string random_engine::get_random_name_corporation() {
  /// Make up a company name
  std::stringstream name;
  name << get_random_name_ancient() << " "
       << corporations[get_random_uint(0, corporations_max)];
  return name.str();
}

std::string random_engine::get_random_colour() {
  /// Pick a random colour
  return colours[get_random_uint(0, colours_max)];
}

const char* const random_engine::greeknames[] = {
  // from http://en.wikipedia.org/wiki/Category:Greek_goddesses
  "Aceso",
  "Achelois",
  "Achlys",
  "Adephagia",
  "Adikia",
  "Adrasteia",
  "Aegiale",
  "Aergia",
  "Aglaea",
  "Aidos",
  "Alala",
  "Alecto",
  "Aletheia",
  "Algos",
  "Amechania",
  "Amphictyonis",
  "Amphilogiai",
  "Amphitrite",
  "Anaideia",
  "Ananke",
  "Androktasiai",
  "Angelia",
  "Antheia",
  "Aoide",
  "Apate",
  "Aphaea",
  "Apollonis",
  "Arae",
  "Arete",
  "Arke",
  "Asia",
  "Astraea",
  "Ate",
  "Atropos",
  "Aura",
  "Benthesikyme",
  "Bia",
  "Bolbe",
  "Borysthenis",
  "Brimo",
  "Britomartis",
  "Brizo",
  "Carme",
  "Caryatis",
  "Cephisso",
  "Ceto",
  "Charites",
  "Circe",
  "Cleta",
  "Clotho",
  "Despoina",
  "Dia",
  "Dike",
  "Dione",
  "Dysnomia",
  "Dyssebeia",
  "Eidyia",
  "Eileithyia",
  "Eirene",
  "Eiresione",
  "Ekecheiria",
  "Electryone",
  "Eleutheria",
  "Elpis",
  "Enodia",
  "Enyo",
  "Eos",
  "Erinyes",
  "Eris",
  "Ersa",
  "Eucleia",
  "Eukarpia",
  "Eunomia",
  "Eunostus",
  "Eupheme",
  "Euphrosyne",
  "Euporie",
  "Eupraxia",
  "Eurybia",
  "Eurydome",
  "Eurynome",
  "Euthenia",
  "Gaia",
  "Galene",
  "Graeae",
  "Harmonia",
  "Hebe",
  "Hegemone",
  "Heimarmene",
  "Heliades",
  "Hemera",
  "Hesperius",
  "Hippeia",
  "Homonoia",
  "Horae",
  "Horme",
  "Hygieia",
  "Hypate",
  "Hysminai",
  "Ialysos",
  "Iaso",
  "Ichnaea",
  "Iris",
  "Kakia",
  "Kale",
  "Kallone",
  "Kamira",
  "Lachesis",
  "Lampad",
  "Lampetia",
  "Lampsace",
  "Lethe",
  "Leto",
  "Leucothea",
  "Limos",
  "Litae",
  "Lyssa",
  "Macaria",
  "Maia",
  "Maniae",
  "Megaera",
  "Melete",
  "Mene",
  "Mese",
  "Metis",
  "Mneme",
  "Mnemosyne",
  "Moirai",
  "Naiad",
  "Nemesis",
  "Nesoi",
  "Nete",
  "Nike",
  "Nyx",
  "Oenotropae",
  "Oizys",
  "Palioxis",
  "Pallas",
  "Panacea",
  "Pandia",
  "Pasikrata",
  "Pasiphae",
  "Pasithea",
  "Pegasides",
  "Peitharchia",
  "Peitho",
  "Penia",
  "Pepromene",
  "Persephone",
  "Phaenna",
  "Pheme",
  "Pherusa",
  "Philophrosyne",
  "Philotes",
  "Phoebe",
  "Phrike",
  "Pistis",
  "Plane",
  "Poena",
  "Potamides",
  "Potnia Theron",
  "Praxidike",
  "Proioxis",
  "Prophasis",
  "Pseudologoi",
  "Ptocheia",
  "Rhapso",
  "Rhea",
  "Rhode",
  "Selene",
  "Tethys",
  "Thalassa",
  "Thalia",
  "Thalia",
  "Theia",
  "Thelxinoe",
  "Themis",
  "Thesis",
  "Tisiphone",
  "Tyche",

  // from http://en.wikipedia.org/wiki/Category:Greek_gods
  "Achelous",
  "Acheron",
  "Adonis",
  "Aegipan",
  "Aeolus",
  "Aesepus",
  "Aether",
  "Aethon",
  "Agathodaemon",
  "Agon",
  "Agreus",
  "Alastor",
  "Alexiares",
  "Anicetus",
  "Alpheus",
  "Anakes",
  "Anapos",
  "Anemoi",
  "Anteros",
  "Aon",
  "Apis",
  "Arche",
  "Aristaeus",
  "Asopus",
  "Asterion",
  "Astraeus",
  "Atlas",
  "Axius",
  "Beroe",
  "Brychon",
  "Caerus",
  "Castor",
  "Pollux",
  "Cebren",
  "Cephissus",
  "Ceraon",
  "Chrysus",
  "Coeus",
  "Comus",
  "Corus",
  "Crius",
  "Cronus",
  "Deimos",
  "Deipneus",
  "Dindymene",
  "Elasioi",
  "Eleos",
  "Enipeus",
  "Enyalius",
  "Epiales",
  "Epimetheus",
  "Epiphron",
  "Eridanos",
  "Erikepaios",
  "Eros",
  "Erotes",
  "Eurus",
  "Evenus",
  "Geras",
  "Glaucus",
  "Harpocrates",
  "Hedylogos",
  "Heimarmene",
  "Hermus",
  "Hesperus",
  "Homados",
  "Homer",
  "Horkos",
  "Horme",
  "Hymen",
  "Hyperion",
  "Hypnos",
  "Iacchus",
  "Iapetus",
  "Inachus",
  "Kladeos",
  "Koalemos",
  "Kratos",
  "Kydoimos",
  "Lelantos",
  "Machai",
  "Maron",
  "Matton",
  "Meander",
  "Meilichios",
  "Melicertes",
  "Menoetius",
  "Momus",
  "Moros",
  "Morpheus",
  "Myiagros",
  "Neikea",
  "Nilus",
  "Nomos",
  "Oceanus",
  "Olethros",
  "Oneiroi",
  "Ophion",
  "Ourea",
  "Paean",
  "Palaemon",
  "Palici",
  "Peneus",
  "Penthus",
  "Pepromene",
  "Phaenon",
  "Phanes",
  "Phantasos",
  "Philomelus",
  "Phobetor",
  "Phobos",
  "Phonoi",
  "Phorcys",
  "Phosphorus",
  "Phrike",
  "Phthonus",
  "Pluto",
  "Plutus",
  "Polemos",
  "Polymatheia",
  "Ponos",
  "Porus",
  "Priapus",
  "Pseudologoi",
  "Pyroeis",
  "Pyrrhichos",
  "Scamander",
  "Simoeis",
  "Spercheus",
  "Stilbon",
  "Telesphorus",
  "Thaumas",
  "Theandrios",
  "Tmolus",
  "Triton",
  "Trophonius",
  "Tychon",
  "Uranus",
  "Zagreus",
  "Zelus"
};
unsigned int const random_engine::greeknames_max = 319;

const char* const random_engine::romannames[] = {
  // from http://en.wikipedia.org/wiki/Category:Roman_goddesses
  "Abeona",
  "Abundantia",
  "Acca Larentia",
  "Aequitas",
  "Aeternitas",
  "Agenoria",
  "Alemonia",
  "Angerona",
  "Angitia",
  "Anna Perenna",
  "Annona",
  "Antevorta",
  "Aura",
  "Aurora",
  "Bellona",
  "Bona",
  "Bubona",
  "Camenae",
  "Candelifera",
  "Cardea",
  "Carmenta",
  "Ceres",
  "Cinxia",
  "Clementia",
  "Cloacina",
  "Concordia",
  "Cuba",
  "Cunina",
  "Cura",
  "Dia",
  "Tacita",
  "Decima",
  "Deverra",
  "Diana",
  "Disciplina",
  "Edusa",
  "Egeria",
  "Empanda",
  "Epona",
  "Fauna",
  "Faustitas",
  "Febris",
  "Fecunditas",
  "Felicitas",
  "Ferentina",
  "Feronia",
  "Fides",
  "Flora",
  "Fornax",
  "Fortuna",
  "Fortuna Huiusce Diei",
  "Fortuna Redux",
  "Fortuna Virilis",
  "Fraus",
  "Fulgora",
  "Furrina",
  "Gallia",
  "Hecate",
  "Hersilia",
  "Hippona",
  "Iana",
  "Invidia",
  "Juno",
  "Lady Justice",
  "Juturna",
  "Juventas",
  "Laetitia",
  "Larentina",
  "Laverna",
  "Levana",
  "Libera",
  "Liberalitas",
  "Libertas",
  "Libitina",
  "Lima",
  "Lua",
  "Lucina",
  "Luna",
  "Lympha",
  "Magna",
  "Mana Genita",
  "Mania",
  "Mater Matuta",
  "Mefitis",
  "Mellona",
  "Minerva",
  "Molae",
  "Moneta",
  "Morta",
  "Murcia",
  "Nascio",
  "Nerio",
  "Nixi",
  "Nona",
  "Ops",
  "Orbona",
  "Palatua",
  "Pales",
  "Parcae",
  "Partula",
  "Patelana",
  "Paventia",
  "Pax",
  "Pellonia",
  "Poena",
  "Pomona",
  "Postverta",
  "Potina",
  "Prorsa Postverta",
  "Proserpina",
  "Providentia",
  "Pudicitia",
  "Puta",
  "Quiritis",
  "Robigo",
  "Roma",
  "Rumina",
  "Rusina",
  "Salacia",
  "Securitas",
  "Semonia",
  "Sentia",
  "Silvanae",
  "Spes",
  "Stata Mater",
  "Strenua",
  "Suadela",
  "Tempestas",
  "Terra",
  "Lares",
  "Tranquillitas",
  "Tutela",
  "Tutelina",
  "Ultio",
  "Vacuna",
  "Vallonia",
  "Venus",
  "Venus Castina",
  "Veritas",
  "Vesta",
  "Vica Pota",
  "Victoria",
  "Viriplaca",
  "Virtus",
  "Volumna",
  "Volutina",

  // from http://en.wikipedia.org/wiki/Category:Roman_gods
  "Adranus",
  "Aius Locutius",
  "Almo",
  "Apollo",
  "Averruncus",
  "Bonus Eventus",
  "Cacus",
  "Caelus",
  "Clitumnus",
  "Consus",
  "Convector",
  "Cupid",
  "Dei Lucrii",
  "Dis Pater",
  "Dius Fidius",
  "Elagabalus",
  "Endovelicus",
  "Evander",
  "Fabulinus",
  "Falacer",
  "Fascinus",
  "Faunus",
  "Feretrius",
  "Fontus",
  "Forculus",
  "Honos",
  "Inuus",
  "Janus",
  "Jugatinus",
  "Jupiter",
  "Jupiter Indiges",
  "Jupiter Tonans",
  "Lactans",
  "Lares",
  "Lateranus",
  "Liber",
  "Limentinus",
  "Lucifer",
  "Mars",
  "Mercury",
  "Momus",
  "Mors",
  "Mutunus Tutunus",
  "Nemausus",
  "Nemestrinus",
  "Neptune",
  "Nodutus",
  "Orcus",
  "Pales",
  "Palici",
  "Picumnus",
  "Picus",
  "Pilumnus",
  "Pluto",
  "Portunes",
  "Porus",
  "Quirinus",
  "Rediculus",
  "Robigus",
  "Sancus",
  "Saritor",
  "Saturn",
  "Silvanus",
  "Sol",
  "Sol Invictus",
  "Soranus",
  "Sors",
  "Spiniensis",
  "Statanus",
  "Sterquilinus",
  "Summanus",
  "Terminus",
  "Tiberinus",
  "Tibertus",
  "Vagitanus",
  "Vejovis",
  "Verminus",
  "Vertumnus",
  "Vervactor",
  "Viduus",
  "Virtus",
  "Volturnus",
  "Vulcan"
};
unsigned int const random_engine::romannames_max = 228;

char const *const random_engine::malenames[] = {};
unsigned int const random_engine::malenames_max = 0;
char const *const random_engine::femalenames[] = {};
unsigned int const random_engine::femalenames_max = 0;
char const *const random_engine::neuternames[] = {};
unsigned int const random_engine::neuternames_max = 0;
char const *const random_engine::surnames[] = {};
unsigned int const random_engine::surnames_max = 0;

char const *const random_engine::corporations[] = {
  "Corporation",
  "Corp",
  "Megacorp",
  "Ltd",
  "Unlimited",
  "PLC",
  "Enterprises",
  "Partnership",
  "Industries",
  "Designs",
  "Heavy Industries",
  "Technologies"
};
unsigned int const random_engine::corporations_max = 12;

char const *const random_engine::colours[] = {
  "Alizarin",
  "Amaranth",
  "Amber",
  "Amethyst",
  "Apricot",
  "Aqua",
  "Aquamarine",
  "Asparagus",
  "Auburn",
  "Azure",
  "Beige",
  "Bistre",
  "Black",
  "Blue",
  "Brass",
  "Bronze",
  "Brown",
  "Buff",
  "Burgundy",
  "Camouflage",
  "Cardinal",
  "Carmine",
  "Carrot orange",
  "Celadon",
  "Cerise",
  "Cerulean",
  "Champagne",
  "Charcoal",
  "Chartreuse",
  "Cherryblossom",
  "Chestnut",
  "Chocolate",
  "Cinnabar",
  "Cinnamon",
  "Cobalt",
  "Copper",
  "Coral",
  "Corn",
  "Cornflower",
  "Cream",
  "Crimson",
  "Cyan",
  "Dandelion",
  "Denim",
  "Ecru",
  "Emerald",
  "Eggplant",
  "Falu",
  "Fern",
  "Firebrick",
  "Flax",
  "Forest",
  "Fuchsia",
  "Gamboge",
  "Gold",
  "Goldenrod",
  "Green",
  "Grey",
  "Harlequin",
  "Heliotrope",
  "Hollywood",
  "Indigo",
  "Ivory",
  "Jade",
  "Khaki",
  "Lavender",
  "Lawn",
  "Lemon",
  "Lilac",
  "Lime",
  "Linen",
  "Magenta",
  "Magnolia",
  "Malachite",
  "Maroon",
  "Mauve",
  "Midnight",
  "Mint",
  "Misty",
  "Moss",
  "Mustard",
  "Myrtle",
  "Navajo",
  "Navy",
  "Ochre",
  "Olive",
  "Olivine",
  "Orange",
  "Orchid",
  "Papaya",
  "Peach",
  "Pear",
  "Periwinkle",
  "Persimmon",
  "Pine",
  "Pink",
  "Platinum",
  "Plum",
  "Powder blue",
  "Puce",
  "Prussian",
  "Psychedelic",
  "Pumpkin",
  "Purple",
  "Quartz",
  "Razzmatazz",
  "Red",
  "Rose",
  "Royal",
  "Ruby",
  "Russet",
  "Rust",
  "Saffron",
  "Salmon",
  "Sandy",
  "Sangria",
  "Sapphire",
  "Scarlet",
  "Seashell",
  "Sepia",
  "Shamrock",
  "Sienna",
  "Silver",
  "Sky",
  "Slate",
  "Smalt",
  "Spring",
  "Steel",
  "Tan",
  "Tangerine",
  "Taupe",
  "Teal",
  "Tan",
  "Tawny",
  "Terracotta",
  "Thistle",
  "Titanium",
  "Tomato",
  "Turquoise",
  "Tyrian",
  "Ultramarine",
  "Umber",
  "Vermilion",
  "Violet",
  "Viridian",
  "Wheat",
  "White",
  "Wisteria",
  "Xanthic",
  "Yellow",
  "Zucchini"
};
unsigned int const random_engine::colours_max = 150;

